package com.roby66one.appexabeatop.model.dataObject

import com.roby66one.appexabeatop.model.businessObject.consumiRegPeriodo.ConsumiRegPeriodoBO
import java.sql.Timestamp


data class ConsumiRegPeriodoDO (
        val anno_mese : Long,
        val id_punto_misura : Long,
        val da_giorno : Long,
        val a_giorno : Long,
        val cons_et1 : Double?,
        val cons_et2 : Double?,
        val cons_et3 : Double?,
        val cons_et4 : Double?,
        val cons_rt1 : Double?,
        val cons_rt2 : Double?,
        val cons_rt3 : Double?,
        val cons_rt4 : Double?,
        val picco_wt1 : Double?,
        val picco_wt2 : Double?,
        val picco_wt3 : Double?,
        val picco_wt4 : Double?,
        val provenienza : String?,
        val fascia_attendibilita : String?,
        val tipo_cons_et1 : String?,
        val tipo_cons_et2 : String?,
        val tipo_cons_et3 : String?,
        val tipo_cons_et4 : String?,
        val codice_mis : String?,
        val matricola_mis : String?,
        val day_min_let : Long?,
        val day_max_let : Long?,
        val dt_inizio_val : Timestamp,
        val dt_fine_val : Timestamp,
        val dt_crea : Timestamp,
        val aut_crea : String?,
        val dt_mod : Double?,
        val aut_mod : String?,
        val flag_lettura_lavoro : String?){

        fun mapperToConsumiRegPeriodoBO() : ConsumiRegPeriodoBO = ConsumiRegPeriodoBO(
                this.anno_mese,
                this.id_punto_misura,
                this.da_giorno,
                this.a_giorno,
                this.cons_et1,
                this.cons_et2,
                this.cons_et3,
                this.cons_et4,
                this.cons_rt1,
                this.cons_rt2,
                this.cons_rt3,
                this.cons_rt4,
                this.picco_wt1,
                this.picco_wt2,
                this.picco_wt3,
                this.picco_wt4,
                this.provenienza,
                this.fascia_attendibilita,
                this.tipo_cons_et1,
                this.tipo_cons_et2,
                this.tipo_cons_et3,
                this.tipo_cons_et4,
                this.codice_mis,
                this.matricola_mis,
                this.day_min_let,
                this.day_max_let,
                this.dt_inizio_val.toLocalDateTime(),
                this.dt_fine_val.toLocalDateTime(),
                this.dt_crea.toLocalDateTime(),
                this.aut_crea,
                this.dt_mod,
                this.aut_mod,
                this.flag_lettura_lavoro
        )

}