package com.roby66one.appexabeatop.model.dataObject

import com.roby66one.appexabeatop.model.businessObject.consumiCdc.ConsumiCdcBO
import java.sql.Timestamp


data class ConsumiCdcDO (
        val id_cdc  : Long,
        val giorno_cdc : Long,
        val id_punto_misura : Long,
        val id_inst_misuratore : Long?,
        val id_obis : Long,
        val id_raccolta_cdc : Double?,
        val id_curva : Double?,
        val id_spezzata : Double?,
        val id_gruppo_misure : Long?,
        val id_tipo_ora : String?,
        val valore_01 : Double,
        val valore_02 : Double,
        val valore_03 : Double,
        val valore_04 : Double,
        val valore_05 : Double,
        val valore_06 : Double,
        val valore_07 : Double,
        val valore_08 : Double,
        val valore_09 : Double,
        val valore_10 : Double,
        val valore_11 : Double,
        val valore_12 : Double,
        val valore_13 : Double,
        val valore_14 : Double,
        val valore_15 : Double,
        val valore_16 : Double,
        val valore_17 : Double,
        val valore_18 : Double,
        val valore_19 : Double,
        val valore_20 : Double,
        val valore_21 : Double,
        val valore_22 : Double,
        val valore_23 : Double,
        val valore_24 : Double,
        val valore_25 : Double,
        val valore_26 : Double,
        val valore_27 : Double,
        val valore_28 : Double,
        val valore_29 : Double,
        val valore_30 : Double,
        val valore_31 : Double,
        val valore_32 : Double,
        val valore_33 : Double,
        val valore_34 : Double,
        val valore_35 : Double,
        val valore_36 : Double,
        val valore_37 : Double,
        val valore_38 : Double,
        val valore_39 : Double,
        val valore_40 : Double,
        val valore_41 : Double,
        val valore_42 : Double,
        val valore_43 : Double,
        val valore_44 : Double,
        val valore_45 : Double,
        val valore_46 : Double,
        val valore_47 : Double,
        val valore_48 : Double,
        val valore_49 : Double,
        val valore_50 : Double,
        val valore_51 : Double,
        val valore_52 : Double,
        val valore_53 : Double,
        val valore_54 : Double,
        val valore_55 : Double,
        val valore_56 : Double,
        val valore_57 : Double,
        val valore_58 : Double,
        val valore_59 : Double,
        val valore_60 : Double,
        val valore_61 : Double,
        val valore_62 : Double,
        val valore_63 : Double,
        val valore_64 : Double,
        val valore_65 : Double,
        val valore_66 : Double,
        val valore_67 : Double,
        val valore_68 : Double,
        val valore_69 : Double,
        val valore_70 : Double,
        val valore_71 : Double,
        val valore_72 : Double,
        val valore_73 : Double,
        val valore_74 : Double,
        val valore_75 : Double,
        val valore_76 : Double,
        val valore_77 : Double,
        val valore_78 : Double,
        val valore_79 : Double,
        val valore_80 : Double,
        val valore_81 : Double,
        val valore_82 : Double,
        val valore_83 : Double,
        val valore_84 : Double,
        val valore_85 : Double,
        val valore_86 : Double,
        val valore_87 : Double,
        val valore_88 : Double,
        val valore_89 : Double,
        val valore_90 : Double,
        val valore_91 : Double,
        val valore_92 : Double,
        val valore_93 : Double,
        val valore_94 : Double,
        val valore_95 : Double,
        val valore_96 : Double,
        val valore_tot : Double,
        val provenienza : String,
        val destinazione : String,
        val stato : String,
        val dt_ins : Timestamp,
        val dt_init_validita : Timestamp,
        val dt_fine_validita : Timestamp,
        val firma : String?,
        val id_aut_ins : Long,
        val flusso : String?,
        val matricola_utente : String?,
        val id_file : Long?,
        val dt_ins_flat : Double?,
        val aut_ins : String?,
        val cvs_revision : String?
){
        fun mapperToConsumiCdcBO() : ConsumiCdcBO = ConsumiCdcBO(
                this.id_cdc,
                this.giorno_cdc,
                this.id_punto_misura,
                this.id_inst_misuratore,
                this.id_obis,
                this.id_raccolta_cdc,
                this.id_curva,
                this.id_spezzata,
                this.id_gruppo_misure,
                this.id_tipo_ora,
                this.valore_01,
                this.valore_02,
                this.valore_03,
                this.valore_04,
                this.valore_05,
                this.valore_06,
                this.valore_07,
                this.valore_08,
                this.valore_09,
                this.valore_10,
                this.valore_11,
                this.valore_12,
                this.valore_13,
                this.valore_14,
                this.valore_15,
                this.valore_16,
                this.valore_17,
                this.valore_18,
                this.valore_19,
                this.valore_20,
                this.valore_21,
                this.valore_22,
                this.valore_23,
                this.valore_24,
                this.valore_25,
                this.valore_26,
                this.valore_27,
                this.valore_28,
                this.valore_29,
                this.valore_30,
                this.valore_31,
                this.valore_32,
                this.valore_33,
                this.valore_34,
                this.valore_35,
                this.valore_36,
                this.valore_37,
                this.valore_38,
                this.valore_39,
                this.valore_40,
                this.valore_41,
                this.valore_42,
                this.valore_43,
                this.valore_44,
                this.valore_45,
                this.valore_46,
                this.valore_47,
                this.valore_48,
                this.valore_49,
                this.valore_50,
                this.valore_51,
                this.valore_52,
                this.valore_53,
                this.valore_54,
                this.valore_55,
                this.valore_56,
                this.valore_57,
                this.valore_58,
                this.valore_59,
                this.valore_60,
                this.valore_61,
                this.valore_62,
                this.valore_63,
                this.valore_64,
                this.valore_65,
                this.valore_66,
                this.valore_67,
                this.valore_68,
                this.valore_69,
                this.valore_70,
                this.valore_71,
                this.valore_72,
                this.valore_73,
                this.valore_74,
                this.valore_75,
                this.valore_76,
                this.valore_77,
                this.valore_78,
                this.valore_79,
                this.valore_80,
                this.valore_81,
                this.valore_82,
                this.valore_83,
                this.valore_84,
                this.valore_85,
                this.valore_86,
                this.valore_87,
                this.valore_88,
                this.valore_89,
                this.valore_90,
                this.valore_91,
                this.valore_92,
                this.valore_93,
                this.valore_94,
                this.valore_95,
                this.valore_96,
                this.valore_tot,
                this.provenienza,
                this.destinazione,
                this.stato,
                this.dt_ins.toLocalDateTime(),
                this.dt_init_validita.toLocalDateTime(),
                this.dt_fine_validita.toLocalDateTime(),
                this.firma,
                this.id_aut_ins,
                this.flusso,
                this.matricola_utente,
                this.id_file,
                this.dt_ins_flat,
                this.aut_ins,
                this.cvs_revision
        )



}