package com.roby66one.appexabeatop.model.dataObject

import com.roby66one.appexabeatop.model.businessObject.valRegCe.ValRegCeBO
import java.sql.Timestamp


data class ValRegCeDO(
        val giorno_lettura : Long,
        val giorno_acq_reg : Long,
        val ora_acq_reg : Long,
        val codice : String,
        val matricola : String,
        val id_punto_misura : Long,
        val eneltel : String,
        val code_provenienza : String?,
        val id_motivo_lettura : Long?,
        val dt_rettifica : Double?,
        val dt_esportazione : Double?,
        val code_cs2 : String?,
        val code_cs3 : String?,
        val code_cs4 : String?,
        val code_cs5 : String?,
        val lettura_validata : Long?,
        val id_periodo_rif : Long?,
        val et1 : Double?,
        val et2 : Double?,
        val et3 : Double?,
        val et4 : Double?,
        val rt1 : Double?,
        val rt2 : Double?,
        val rt3 : Double?,
        val rt4 : Double?,
        val wt1 : Double?,
        val wt2 : Double?,
        val wt3 : Double?,
        val wt4 : Double?,
        val psn : Long?,
        val pse : Long?,
        val vpp : Long?,
        val ntvd : Long?,
        val cod_let : String?,
        val data_lettura : Timestamp?,
        val tsen : Long?,
        val disi : Long?,
        val idlotto : Long?,
        val stato_elab : String?,
        val dt_fine_val : Timestamp?,
        val aut_mod : String?,
        val aut_crea : String?,
        val dt_inizio_val : Timestamp?,
        val dt_mod : Timestamp?
        ){

        fun mapperToValRegCeBO() : ValRegCeBO = ValRegCeBO(
                this.giorno_lettura,
                this.giorno_acq_reg,
                this.ora_acq_reg,
                this.codice,
                this.matricola,
                this.id_punto_misura,
                this.eneltel,
                this.code_provenienza,
                this.id_motivo_lettura,
                this.dt_rettifica,
                this.dt_esportazione,
                this.code_cs2,
                this.code_cs3,
                this.code_cs4,
                this.code_cs5,
                this.lettura_validata,
                this.id_periodo_rif,
                this.et1,
                this.et2,
                this.et3,
                this.et4,
                this.rt1,
                this.rt2,
                this.rt3,
                this.rt4,
                this.wt1,
                this.wt2,
                this.wt3,
                this.wt4,
                this.psn,
                this.pse,
                this.vpp,
                this.ntvd,
                this.cod_let,
                this.data_lettura?.toLocalDateTime(),
                this.tsen,
                this.disi,
                this.idlotto,
                this.stato_elab,
                this.dt_fine_val?.toLocalDateTime(),
                this.aut_mod,
                this.aut_crea,
                this.dt_inizio_val?.toLocalDateTime(),
                this.dt_mod?.toLocalDateTime()
        )
}